version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: tiktok_simple_pg
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: guang
        POSTGRES_PASSWORD: 123
        POSTGRES_DB: tiktok_simple
    volumes:
      - ../postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
